### PR TITLE
Comply with PHP 8.1 specs for interfaces.

### PR DESCRIPTION
**Pull request by antoineveldhoven**
Comply with PHP 8.1 specs for ArrayAccess and Countable interfaces.

### CODE REVIEW

**Comment by robbinjanssen** [comment]
This change makes the package incompatible with PHP 7.x. You need to change the composer.json file as well (to only accept PHP 8^), then we can make a breaking change and support PHP 7 on previous versions (v3.x).

**Comment by robbinjanssen** [comment]
@antoineveldhoven this got a little more prio and we will fix this in #31. So I will close this PR :-) We'll give you an update when it is done.

**Comment by robbinjanssen** [comment]
@antoineveldhoven [v3.1.3](https://github.com/exonet/exonet-api-php/releases/tag/v3.1.3) has been released adding support for PHP 8.1 🎉

**Comment by antoineveldhoven** [comment]
🎉 thanx for the fix!

**Pull request closed without merging**
